In [5]:
# 구간 분할

import pandas as pd
import numpy as np

df = pd.read_csv("./data/auto-mpg.csv", header=None)

df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'name']

df['horsepower'] = df['horsepower'].replace('?', np.nan)
df = df.dropna(subset=['horsepower'], axis=0)
df['horsepower'] = df['horsepower'].astype(float)


count, bin_divisers = np.histogram(df['horsepower'], bins=3)
print(bin_divisers)

print(count)

[ 46.         107.33333333 168.66666667 230.        ]
[257 103  32]

In [12]:
bin_names = ['저출력', '보통출력', '고출력']

df['hp_bin']=pd.cut(x = df['horsepower'],
                    bins = bin_divisers,
                    labels=bin_names,
                    include_lowest=True)


df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,hp_bin
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,보통출력
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,보통출력
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,보통출력
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,보통출력
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,보통출력

In [13]:
bin_divisers

array([ 46.        , 107.33333333, 168.66666667, 230.        ])

In [14]:
df[['horsepower', 'hp_bin']].head(15)

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

In [17]:
# 변수더미

horsepower_dummies = pd.get_dummies(df['hp_bin'])
horsepower_dummies.head(10)

     저출력   보통출력    고출력
0  False   True  False
1  False   True  False
2  False   True  False
3  False   True  False
4  False   True  False
5  False  False   True
6  False  False   True
7  False  False   True
8  False  False   True
9  False  False   True

In [21]:
horsepower_dummies_float = pd.get_dummies(df['hp_bin'], dtype=float)
horsepower_dummies_float.head(16)

    저출력  보통출력  고출력
0   0.0   1.0  0.0
1   0.0   1.0  0.0
2   0.0   1.0  0.0
3   0.0   1.0  0.0
4   0.0   1.0  0.0
5   0.0   0.0  1.0
6   0.0   0.0  1.0
7   0.0   0.0  1.0
8   0.0   0.0  1.0
9   0.0   0.0  1.0
10  0.0   0.0  1.0
11  0.0   1.0  0.0
12  0.0   1.0  0.0
13  0.0   0.0  1.0
14  1.0   0.0  0.0
15  1.0   0.0  0.0

In [27]:
horsepower_dummies_drop = pd.get_dummies(df['hp_bin'], dtype=float, drop_first=True)
horsepower_dummies_drop.head()

   보통출력  고출력
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   1.0  0.0

In [37]:
from sklearn import preprocessing as pre

label_encoder = pre.LabelEncoder()
onehot_encoder = pre.OneHotEncoder()

onehot_labeled = label_encoder.fit_transform(df['hp_bin'].head(15))
print(onehot_labeled)
print(type(onehot_labeled))

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
<class 'numpy.ndarray'>

In [38]:
onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled), 1)
print(onehot_reshaped)
print(type(onehot_reshaped))

[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]
<class 'numpy.ndarray'>

In [40]:
onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)
print(type(onehot_fitted))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (15, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>