In [ ]:
# 

import requests
import pandas as pd

my_key = ""

def get_geocoding(place):
    url = f"https://dapi.kakao.com/v2/local/search/address.json?query={place}"
    headers = {"Authorization": f"KakaoAK {my_key}"}
    response = requests.get(url, headers = headers)
    result = response.json()

    # print(result["documents"][0]["y"])
    # print(result["documents"][0]["x"])
    return result["documents"][0]["y"], result["documents"][0]["x"]

lat = []
lng = []

places = ["대구 북구 대학로 80",
          "경북 구미시 대학로 61",
          "경북대학교",
          "대구 남구 명덕로 104"]

i = 0

for place in places:
    i += 1
    try:
        print(i, place)
        place_lat, place_lon = get_geocoding(place)
        lat.append(place_lat)
        lng.append(place_lon)

    except:
        lat.append('')
        lng.append('')
        print(i)

dict_data = {
    '위도': lat,
    '경도': lng
}

df = pd.DataFrame(dict_data, index=places)
df

1 대구 북구 대학로 80
2 경북 구미시 대학로 61
3 경북대학교
3
4 대구 남구 명덕로 104

                             위도                경도
대구 북구 대학로 80   35.8890974884948  128.614322336303
경북 구미시 대학로 61  36.1456601455539  128.388119702872
경북대학교
대구 남구 명덕로 104  35.8555231686465  128.579315744509

In [ ]:
# data.go.kr
# 국토교통부 아파트 매매 실거래가 자료

import requests
import xml.etree.ElementTree as ET
import pandas as pd

SERVICE_KEY = ""
url = "https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade?"

def fetch_apt_trade(servicekey, LAWD_CD, DEAL_YMD):
    params = {
        'serviceKey' : servicekey,
        'LAWD_CD' : LAWD_CD,
        'DEAL_YMD': DEAL_YMD
    }
    
    response = requests.get(url, params = params)
    # print(response.content)
    root = ET.fromstring(response.content)
    # print(root)
    items = root.findall(".//item")
    # print(items)
    records = []
    for item in items:
        row = {}

        for child in item:
            row[child.tag] = child.text

        records.append(row)

    return records


data = fetch_apt_trade(SERVICE_KEY, LAWD_CD = "27200", DEAL_YMD = '202604')

df = pd.DataFrame(data)
print(df.shape)
df

(10, 20)

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,dealingGbn,estateAgentSggNm,excluUseAr,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm
0,,교대역하늘채뉴센트원,2022,개인,,,"32,000",30,4,2026,중개거래,대구 남구,49.7491,15,3067,N,,27200,개인,대명동
1,,교대역하늘채뉴센트원,2022,개인,,,"53,200",25,4,2026,중개거래,대구 남구,74.7212,14,3067,N,,27200,개인,대명동
2,,"힐스테이트대명센트럴(103,104동)",2025,개인,,,"61,000",22,4,2026,중개거래,대구 남구,84.5272,32,3079,N,,27200,개인,대명동
3,,보성청록타운,1998,개인,,,"16,500",3,4,2026,중개거래,대구 남구,59.79,11,2680-17,N,,27200,개인,대명동
4,,희망교대성유니드,2006,개인,,,"27,000",25,4,2026,중개거래,대구 남구,84.9613,4,361-16,N,,27200,개인,이천동
5,,대명역센트럴엘리프,2022,개인,,,"54,500",19,4,2026,중개거래,대구 남구,84.6292,19,3072,N,,27200,개인,대명동
6,,드림팰리스,2016,개인,,,"23,000",17,4,2026,중개거래,대구 남구,84.0838,3,1623-14,N,,27200,개인,대명동
7,C,새한(1701-2),1979,개인,,,"20,000",17,4,2026,직거래,,73.19,2,1701-2,N,26.05.08,27200,개인,대명동
8,,대구이천주공1,1999,개인,,,"26,800",24,4,2026,중개거래,대구 남구,84.98,6,121-70,N,,27200,개인,이천동
9,,대구이천주공1,1999,개인,,,"19,250",9,4,2026,중개거래,대구 남구,59.96,15,121-70,N,,27200,개인,이천동

In [ ]:
mport requests
import pandas as pd


url = "https://apis.data.go.kr/B552696/countrygrade/credit-grade"
SERVICE_KEY = ""

def country_credit_rating(page_no=1, num_of_row=100):
    params = {
        'serviceKey' : SERVICE_KEY,
        'pageNo' : page_no,
        'numOfRows' : num_of_row
    }

    response = requests.get(url, params = params)

    results = response.json()
    print(results)

country_credit_rating(1, 100)

{'response': {'header': {'resultCode': 0, 'resultMsg': 'NORMAL SERVICE.'}, 'body': {'items': {'item': [{'ctryCd': 'GH', 'ctryNm': '가나', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GA', 'ctryNm': '가봉', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GY', 'ctryNm': '가이아나', 'evalGrd': '5', 'evalDd': '20251017'}, {'ctryCd': 'GM', 'ctryNm': '감비아', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GP', 'ctryNm': '과달루프', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'GT', 'ctryNm': '과테말라', 'evalGrd': '4', 'evalDd': '20251017'}, {'ctryCd': 'GU', 'ctryNm': '괌', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'GD', 'ctryNm': '그레나다', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': 'GR', 'ctryNm': '그리스', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': 'GL', 'ctryNm': '그린랜드', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'GN', 'ctryNm': '기니', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GW', 'ctryNm': '기니비사우', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'NA', 'ctryNm': '나미비아', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'UM', 'ctryNm': '나바사섬', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NR', 'ctryNm': '나우루', 'evalGrd': '3', 'evalDd': '20241121'}, {'ctryCd': 'NG', 'ctryNm': '나이지리아', 'evalGrd': '6', 'evalDd': '20251017'}, {'ctryCd': 'SS', 'ctryNm': '남수단', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'ZA', 'ctryNm': '남아프리카공화국', 'evalGrd': '4', 'evalDd': '20250703'}, {'ctryCd': 'GS', 'ctryNm': '남조지아.남샌드위치군도', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NL', 'ctryNm': '네덜란드', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'NP', 'ctryNm': '네팔', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'NO', 'ctryNm': '노르웨이', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': None, 'ctryNm': '노르웨이속령', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NF', 'ctryNm': '노포크 아일랜드', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NZ', 'ctryNm': '뉴질랜드', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'NC', 'ctryNm': '뉴칼레도니아', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': 'NU', 'ctryNm': '니우에', 'evalGrd': '5', 'evalDd': '20251230'}, {'ctryCd': 'NE', 'ctryNm': '니제르', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'NI', 'ctryNm': '니카라과', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'TW', 'ctryNm': '대만', 'evalGrd': '2', 'evalDd': '20250703'}, {'ctryCd': 'KR', 'ctryNm': '대한민국', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'DK', 'ctryNm': '덴마크', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'DM', 'ctryNm': '도미니카 연방', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': 'DO', 'ctryNm': '도미니카공화국', 'evalGrd': '4', 'evalDd': '20251017'}, {'ctryCd': 'DE', 'ctryNm': '독일', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'TL', 'ctryNm': '동티모르', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'LA', 'ctryNm': '라오스', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'LR', 'ctryNm': '라이베리아', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'LV', 'ctryNm': '라트비아', 'evalGrd': '2', 'evalDd': '20251230'}, {'ctryCd': 'RU', 'ctryNm': '러시아', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'LB', 'ctryNm': '레바논', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'LS', 'ctryNm': '레소토', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'RE', 'ctryNm': '레위니옹', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': None, 'ctryNm': '로스속령', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'RO', 'ctryNm': '루마니아', 'evalGrd': '3', 'evalDd': '20260206'}, {'ctryCd': 'LU', 'ctryNm': '룩셈부르크', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'RW', 'ctryNm': '르완다', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'LY', 'ctryNm': '리비아', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'LT', 'ctryNm': '리투아니아', 'evalGrd': '2', 'evalDd': '20251230'}, {'ctryCd': 'LI', 'ctryNm': '리히텐슈타인', 'evalGrd': '1', 'evalDd': '20241121'}, {'ctryCd': 'MG', 'ctryNm': '마다가스카르', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'MH', 'ctryNm': '마샬군도', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': 'YT', 'ctryNm': '마요뜨', 'evalGrd': '5', 'evalDd': '20251230'}, {'ctryCd': 'MO', 'ctryNm': '마카오', 'evalGrd': '2', 'evalDd': '20241121'}, {'ctryCd': 'MW', 'ctryNm': '말라위', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'MY', 'ctryNm': '말레이시아', 'evalGrd': '2', 'evalDd': '20250703'}, {'ctryCd': 'ML', 'ctryNm': '말리', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'MQ', 'ctryNm': '말티니크', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'IM', 'ctryNm': '맨섬', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'MX', 'ctryNm': '멕시코', 'evalGrd': '3', 'evalDd': '20251017'}, {'ctryCd': 'ES', 'ctryNm': '멜리야', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': 'MC', 'ctryNm': '모나코', 'evalGrd': '2', 'evalDd': '20241121'}, {'ctryCd': 'MA', 'ctryNm': '모로코', 'evalGrd': '3', 'evalDd': '20260206'}, {'ctryCd': 'MU', 'ctryNm': '모리셔스', 'evalGrd': '3', 'evalDd': '20250703'}, {'ctryCd': 'MR', 'ctryNm': '모리타니아', 'evalGrd': '6', 'evalDd': '20251017'}, {'ctryCd': 'MZ', 'ctryNm': '모잠비크', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'ME', 'ctryNm': '몬테네그로', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'MS', 'ctryNm': '몬트세라트', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'MD', 'ctryNm': '몰도바', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'MV', 'ctryNm': '몰디브', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'MT', 'ctryNm': '몰타', 'evalGrd': '2', 'evalDd': '20231006'}, {'ctryCd': 'MN', 'ctryNm': '몽골', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'US', 'ctryNm': '미국', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'VI', 'ctryNm': '미국령 버진군도', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'AS', 'ctryNm': '미국령 사모아', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': None, 'ctryNm': '미드웨이섬', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'MM', 'ctryNm': '미얀마', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'FM', 'ctryNm': '미크로네시아', 'evalGrd': '6', 'evalDd': '20241121'}, {'ctryCd': 'VU', 'ctryNm': '바누아투', 'evalGrd': '6', 'evalDd': '20241121'}, {'ctryCd': 'BH', 'ctryNm': '바레인', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'BB', 'ctryNm': '바베이도스', 'evalGrd': '6', 'evalDd': '20241121'}, {'ctryCd': 'VA', 'ctryNm': '바티칸', 'evalGrd': '2', 'evalDd': '20241121'}, {'ctryCd': 'BS', 'ctryNm': '바하마', 'evalGrd': '4', 'evalDd': '20251017'}, {'ctryCd': 'BD', 'ctryNm': '방글라데시', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'BM', 'ctryNm': '버뮤다', 'evalGrd': '2', 'evalDd': '20251230'}, {'ctryCd': 'VE', 'ctryNm': '베네수엘라', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'BJ', 'ctryNm': '베넹', 'evalGrd': '6', 'evalDd': '20251017'}, {'ctryCd': None, 'ctryNm': '베이커홀랜드섬', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'VN', 'ctryNm': '베트남', 'evalGrd': '4', 'evalDd': '20250703'}, {'ctryCd': 'BE', 'ctryNm': '벨기에', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'BY', 'ctryNm': '벨라루스', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'BZ', 'ctryNm': '벨리즈', 'evalGrd': '7', 'evalDd': '20231006'}, {'ctryCd': 'BA', 'ctryNm': '보스니아-헤르체코비나', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'BW', 'ctryNm': '보츠와나', 'evalGrd': '3', 'evalDd': '20250703'}, {'ctryCd': 'BO', 'ctryNm': '볼리비아', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'BI', 'ctryNm': '부룬디', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'BF', 'ctryNm': '부르키나파소', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'BT', 'ctryNm': '부탄', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'MP', 'ctryNm': '북마리아나 군도', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'MK', 'ctryNm': '북마케도니아', 'evalGrd': '5', 'evalDd': '20260206'}]}, 'pageNo': 1, 'totalCount': 259, 'numOfRows': 100}}}